### ISSUE TITLE
Error starting clockwork in production

### ISSUE THREAD

**Issue by swilliams** [adamwiggins/clockwork#6]
Trying to run `clockwork lib/clock.rb` on my production server gives this error:

/mysql_adapter.rb:614:in `real_connect': Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) (Mysql::Error)

From what I can tell, it's trying to connect to the development instance of the database. My production config looks like this:

```
production:
  adapter: mysql
  encoding: utf8
  *snip*
  socket: /var/run/mysqld/mysqld.sock
```

I've trying running it via `clockwork lib/clock.rb RAILS_ENV=production` but that didn't work either.

Rails 3.0.7, on nginx & ubuntu (if that matters)
